In [78]:
data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

In [61]:
with open("AoC_D8_data.txt", "r") as f:
    data = f.read()

In [79]:
import pandas as pd
antennas = pd.DataFrame([list(row) for row in data.split("\n")])
antennas

   0  1  2  3  4  5  6  7  8  9  10 11
0   .  .  .  .  .  .  .  .  .  .  .  .
1   .  .  .  .  .  .  .  .  0  .  .  .
2   .  .  .  .  .  0  .  .  .  .  .  .
3   .  .  .  .  .  .  .  0  .  .  .  .
4   .  .  .  .  0  .  .  .  .  .  .  .
5   .  .  .  .  .  .  A  .  .  .  .  .
6   .  .  .  .  .  .  .  .  .  .  .  .
7   .  .  .  .  .  .  .  .  .  .  .  .
8   .  .  .  .  .  .  .  .  A  .  .  .
9   .  .  .  .  .  .  .  .  .  A  .  .
10  .  .  .  .  .  .  .  .  .  .  .  .
11  .  .  .  .  .  .  .  .  .  .  .  .

In [80]:
antenna_types = []
for c in antennas.columns:
    antenna_types += antennas[c].replace({".":None}).dropna().unique().tolist()
antenna_types = list(set(antenna_types))
antenna_types

['A', '0']

In [81]:
def get_all_antennas_pairs(antennas, antenna_type):
    pos = []
    for x in antennas.columns:
        ys = antennas.loc[antennas[x]==antenna_type, x].index.tolist()
        pos += [(x, y) for y in ys]
    return [(p1, p2) for idx, p1 in enumerate(pos) for p2 in pos[idx + 1:]]
get_all_antennas_pairs(antennas, "A")

[((6, 5), (8, 8)), ((6, 5), (9, 9)), ((8, 8), (9, 9))]

In [82]:
antinodes = pd.DataFrame(data = '', columns=antennas.columns, index = antennas.index)

In [83]:
#part 1
for antenna_type in antenna_types:
    # print(antenna_type)
    pairs = get_all_antennas_pairs(antennas, antenna_type)
    for pair in pairs:
        # print(pair)
        a1 = pair[0]
        a2 = pair[1]
        an1 = (a1[0] - (a2[0]-a1[0]), a1[1] - (a2[1]-a1[1]))
        an2 = (a2[0] + (a2[0]-a1[0]), a2[1] + (a2[1]-a1[1]))
        if (0 <= an1[0] < len(antennas.columns)) & (0 <= an1[1] < len(antennas.index)):
            antinodes.loc[an1[1], an1[0]] = "#"
        if (0 <= an2[0] < len(antennas.columns)) & (0 <= an2[1] < len(antennas.index)):
            antinodes.loc[an2[1], an2[0]] = "#"
print((antinodes=="#").sum().sum())
antinodes

14

   0  1  2  3  4  5  6  7  8  9  10 11
0                     #              #
1            #
2               #                 #
3         #
4                              #
5      #              #
6            #
7   #                    #
8
9
10                                #
11                                #

In [84]:
# part 2
for antenna_type in antenna_types:
    # print(antenna_type)
    pairs = get_all_antennas_pairs(antennas, antenna_type)
    for pair in pairs:
        # print(pair)
        a1 = pair[0]
        a2 = pair[1]
        for i in range(len(antennas.columns)+1):
            an1 = (a1[0] - i*(a2[0]-a1[0]), a1[1] - i*(a2[1]-a1[1]))
            an2 = (a2[0] + i*(a2[0]-a1[0]), a2[1] + i*(a2[1]-a1[1]))
            if (0 <= an1[0] < len(antennas.columns)) & (0 <= an1[1] < len(antennas.index)):
                antinodes.loc[an1[1], an1[0]] = "#"
            if (0 <= an2[0] < len(antennas.columns)) & (0 <= an2[1] < len(antennas.index)):
                antinodes.loc[an2[1], an2[0]] = "#"
print((antinodes=="#").sum().sum())
antinodes

34

   0  1  2  3  4  5  6  7  8  9  10 11
0   #  #              #              #
1      #     #              #
2         #     #  #              #
3         #  #           #
4               #              #
5      #           #  #              #
6            #        #
7   #              #     #
8         #                 #
9               #              #
10     #                          #
11           #                    #  #